Repository mz106/climbing-buddy-fe, pull requests merged in 2022-07, with the labels that each got.

#26 first
  docs/deivydas-test.md
Labels: documentation

#27 Documentation
  docs/deivydas-test.md
Labels: documentation

#29 Landing page test
  docs/deivydas-test.md
  src/pages/landingPage/LandingPage.js
Labels: enhancement

#30 Landing page
  src/pages/landingPage/LandingPage.js
Labels: enhancement

#39 #37 Test text added
  docs/markus-test.md
Labels: documentation

#48 Landing page build
  src/App.css
  src/pages/landingPage/Images/wallpaper.jpg
  src/pages/landingPage/LandingPage.css
  src/pages/landingPage/LandingPage.js
Labels: enhancement

#49 Documentation
  docs/flowchart-user-login.drawio
  docs/flowchart-user-signup.drawio
  docs/landing-page-design/landing page design.drawio
Labels: documentation

#46 #45 Created the api requests functions for the user, moved the files …
  src/functions/signupOrLogin/fetchRequests/fetchRequests.js
Labels: enhancement

#51 Landing page
  src/App.css
  src/pages/landingPage/Images/wallpaper.jpg
  src/pages/landingPage/LandingPage.css
  src/pages/landingPage/LandingPage.js
Labels: enhancement

#55 #25 Footer wireframes added to documentation branch
  docs/footer-design/Climb buddy -footer design.fig
  docs/footer-design/Footer_desktop.jpg
  docs/footer-design/Footer_mobile.jpg
  docs/footer-design/figma_link.md
Labels: documentation

#54 Enhancement/footer start
  docs/markus-test.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/UI/footer/CSS/Footer.css
  src/components/UI/footer/CSS/Footer.css.map
  src/components/UI/footer/CSS/Footer.scss
  src/components/UI/footer/Footer.js
  src/components/UI/landingPage/splash/Splash.js
  src/pages/landingPage/LandingPage.js
Labels: enhancement

#58 Navbar/wireframe
  docs/Navbar_wireframe/Untitled Diagram.drawio.drawio
  docs/flowchart-user-login.drawio
  docs/flowchart-user-signup.drawio
  docs/landing-page-design/landing page design.drawio
  docs/markus-test.md
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/UI/footer/Footer.js
  src/components/UI/header/Header.js
  src/components/UI/header/navbar/Navbar.js
  src/components/UI/signOrLogin/SignOrLogin.js
  src/components/header/Header.js
  src/functions/signupOrLogin/fetchRequests/fetchRequests.js
  src/functions/signupOrLogin/helpers/helpers.js
  src/index.js
  src/pages/landingPage/Images/wallpaper.jpg
  src/pages/landingPage/LandingPage.css
  src/pages/landingPage/LandingPage.js
Labels: documentation, enhancement

#60 Header/navbar
  docs/Navbar_wireframe/Untitled Diagram.drawio.drawio
Labels: documentation
